name: apd
description: Aplicativo para assistencia psicologica aos docentes


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  flutter_auth: ^0.0.1
  form_field_validator: ^1.1.0
  top_snackbar_flutter: ^2.1.1
  google_fonts: ^2.2.0
  flutter_spinkit: ^5.1.0
  flutter_animate: ^2.0.1
  


  #cloud_firestore: ^3.1.5
  #firebase_auth: ^3.11.2

dev_dependencies:
  onboarding: ^3.1.0
  smooth_page_indicator: ^1.0.0
  shared_preferences: 2.0.11
  

  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.10
  


flutter_native_splash:
  color: "#b0df9a"
  image: assets/screen_splash/LoadingLogo.png

  size: 2000 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/transition/
    - assets/icons/screenLogin/icons/
    - assets/images/
    - assets/images/screenLogin/images/
    - assets/screen_splash/

 
